### ISSUE TITLE
Providing location to Cargo.toml 

### ISSUE THREAD

**Issue by dzieciou** [doublify/pre-commit-rust#8]
I have repository that has both Python and Rust code inside.

In the root of the repository I have `.pre-commit-config.yaml` with:

```yaml
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
```	  
	  
In the `Rust_code/` folder I have rust code together with `Cargo.toml`.

However, it looks like the hook expects `Cargo.toml` to be in the root of the repository.

```
Error during execution of `cargo metadata`: error: could not find `Cargo.toml` in `D:\projects\project-repo` or any parent directory
```

I see no option for rustfmt to provide path to `Cargo.toml`, only to `rustfmt.toml`.
```
rustfmt -h
...
  --config-path [Path for the configuration file]
                        Recursively searches the given path for the
                        rustfmt.toml config file. If not found reverts to the
                        input file path
```
What options do I have?
